version: "3"

tasks:
  up:
    desc: "dokcer-compose up"
    dir: .
    cmds:
      - "docker-compose up"

  upd:
    desc: "docker-compose up -d"
    dir: .
    cmds:
      - "docker-compose up -d"

  migrate:
    desc: "influxDB migration"
    dir: .
    cmds:
      - "docker-compose exec -T influxdb influx -execute 'CREATE DATABASE cadvisor'"

  down:
    desc: "docker-compose down"
    dir: .
    cmds:
      - "docker-compose down"

  destroy:
    desc: "docker-compose down -v"
    dir: .
    cmds:
      - "docker-compose down -v"
